# Generated by Django 4.1.5 on 2023-02-08 13:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hesabat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title1', models.CharField(blank=True, max_length=10000, null=True)),
                ('title2', models.CharField(blank=True, max_length=10000, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description2', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'hesabat',
                'verbose_name_plural': 'hesabat',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Rəhbər',
                'verbose_name_plural': 'Rəhbərlər',
            },
        ),
        migrations.CreateModel(
            name='Ugur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title1', models.CharField(blank=True, max_length=10000, null=True)),
                ('title2', models.CharField(blank=True, max_length=10000, null=True)),
                ('description1', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description2', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('facebook', models.CharField(blank=True, max_length=120, null=True)),
                ('twitter', models.CharField(blank=True, max_length=120, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Uğur Hekayəsi',
                'verbose_name_plural': 'Uğur Hekayələri',
            },
        ),
    ]
