# Generated by Django 4.1.5 on 2023-01-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anasahifa', '0002_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='logo7',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
