# Generated by Django 4.1.5 on 2023-01-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anasahifa', '0003_selector_logo7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=220)),
                ('instagram', models.CharField(max_length=220)),
                ('whatsapp', models.CharField(max_length=220)),
                ('linkedin', models.CharField(max_length=220)),
            ],
        ),
    ]
