# Generated by Django 4.1.5 on 2023-02-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anasahifa', '0006_alter_home_image_alter_selector_logo1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Açıqlama', 'verbose_name_plural': 'Açıqlama'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Ana Səhifə', 'verbose_name_plural': 'Ana Səhifə'},
        ),
        migrations.AlterModelOptions(
            name='selector',
            options={'verbose_name': 'Logolar', 'verbose_name_plural': 'Logolar'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Sosiallar', 'verbose_name_plural': 'Sosiallar'},
        ),
    ]
